# Dataset Maker

- Author: Wen Xin
- Description: This file is used to add more kitchen related features in this model to make a new dataset.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings("ignore")

In [11]:
data=pd.read_csv('data_final_2.csv')

In [12]:
len(data)

191855

In [4]:
kitchen_royalty=pd.read_csv('kitchen_royalty.csv')

In [5]:
len(kitchen_royalty)

191855

In [10]:
kitchen_royalty.head(30)

      user_id  kitchen_royalty
0   100002020         1.875000
1   100002033         1.833333
2   100002035         2.600000
3   100002036         2.250000
4   100002040         1.363636
5   100002041         1.000000
6   100002044         1.300000
7   100002050         1.500000
8   100002052         2.230769
9   100002053         1.000000
10  100002078         1.621622
11  100002079         1.000000
12  100002083         1.538462
13  100002085         4.000000
14  100002097         2.000000
15  100002098         1.333333
16  100002108         5.000000
17  100002113         1.350000
18  100002133         1.000000
19  100002135         1.000000
20  100002165         2.333333
21  100002168         1.157895
22  100002201         2.000000
23  100002214        19.000000
24  100002217        18.000000
25  100002223         4.200000
26  100002247         1.200000
27  100002347         1.750000
28  100002348        22.000000
29  100002415         1.166667

In [7]:
most_f_kitchen_info=pd.read_csv('most_freq_kitchen_info.csv')

In [8]:
len(most_f_kitchen_info)

191855

In [9]:
most_f_kitchen_info.head(30)

,user_id,kitchen_id,freq_kitchen_order_nums,city_id,age,staple_price,like_num,is_refectory,hold_num,type,level,star,dummy_like_num,dummy_hold_num,dummy_star,dummy_has_kitchen_info
0,100002020,22750,8,110100.0,70.0,2.0,11.0,1.0,7.0,0.0,2.0,5.0,1.0,1.0,1.0,1
1,100002033,146055,10,330100.0,50.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1
2,100002035,9805,7,110100.0,60.0,2.0,116.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
3,100002036,23974,5,110100.0,70.0,3.0,40.0,1.0,2.0,0.0,2.0,5.0,1.0,1.0,1.0,1
4,100002040,54723,2,110100.0,80.0,2.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,1.0,0.0,1
5,100002041,23510,1,110100.0,70.0,2.0,124.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
6,100002044,156430,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
7,100002050,165775,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
8,100002052,13511,26,110100.0,80.0,3.0,173.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
9,100002053,30,1,110100.0,80.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,1.0,0.0,1
10,100002078,150366,5,110100.0,80.0,2.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,1.0,0.0,1
11,100002079,145371,1,110100.0,60.0,3.0,0.0,0.0,20.0,0.0,2.0,0.0,0.0,1.0,0.0,1
12,100002083,141807,6,440300.0,80.0,2.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,1.0,0.0,1
13,100002085,23476,9,110100.0,80.0,2.0,128.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
14,100002097,29033,2,110100.0,60.0,2.0,55.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
15,100002098,73282,2,440100.0,70.0,1.0,31.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
16,100002108,953,5,110100.0,50.0,1.0,113.0,0.0,0.0,0.0,2.0,5.0,1.0,0.0,1.0,1
17,100002113,44959,3,110100.0,70.0,3.0,60.0,0.0,12.0,0.0,2.0,5.0,1.0,1.0,1.0,1
18,100002133,16182,1,110100.0,60.0,2.0,96.0,0.0,0.0,0.0,2.0,5.0,1.0,0.0,1.0,1
19,100002135,132610,1,110100.0,60.0,2.0,2.0,0.0,1.0,0.0,2.0,0.0,1.0,1.0,0.0,1
20,100002165,42289,5,110100.0,80.0,2.0,51.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
21,100002168,163930,2,110100.0,90.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1
22,100002201,27773,2,110100.0,60.0,2.0,62.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
23,100002214,234,36,110100.0,70.0,2.0,178.0,0.0,0.0,0.0,2.0,5.0,1.0,0.0,1.0,1
24,100002217,234,18,110100.0,70.0,2.0,178.0,0.0,0.0,0.0,2.0,5.0,1.0,0.0,1.0,1
25,100002223,89067,9,110100.0,70.0,2.0,21.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
26,100002247,20317,2,110100.0,80.0,2.0,150.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
27,100002347,13846,3,110100.0,60.0,1.0,132.0,0.0,1.0,0.0,2.0,5.0,1.0,1.0,1.0,1
28,100002348,234,22,110100.0,70.0,2.0,178.0,0.0,0.0,0.0,2.0,5.0,1.0,0.0,1.0,1
29,100002415,64907,2,110100.0,80.0,2.0,47.0,0.0,0.0,0.0,2.0,5.0,1.0,0.0,1.0,1

In [22]:
kitchen_info=most_f_kitchen_info[['user_id','staple_price','like_num','dummy_like_num','dummy_has_kitchen_info']]

In [23]:
kitchen_info.head(30)

      user_id  staple_price  like_num  dummy_like_num  dummy_has_kitchen_info
0   100002020           2.0      11.0             1.0                       1
1   100002033           1.0       0.0             0.0                       1
2   100002035           2.0     116.0             1.0                       1
3   100002036           3.0      40.0             1.0                       1
4   100002040           2.0       0.0             0.0                       1
5   100002041           2.0     124.0             1.0                       1
6   100002044           NaN       NaN             NaN                       0
7   100002050           NaN       NaN             NaN                       0
8   100002052           3.0     173.0             1.0                       1
9   100002053           1.0       0.0             0.0                       1
10  100002078           2.0       0.0             0.0                       1
11  100002079           3.0       0.0             0.0                       1
12  100002083           2.0       0.0             0.0                       1
13  100002085           2.0     128.0             1.0                       1
14  100002097           2.0      55.0             1.0                       1
15  100002098           1.0      31.0             1.0                       1
16  100002108           1.0     113.0             1.0                       1
17  100002113           3.0      60.0             1.0                       1
18  100002133           2.0      96.0             1.0                       1
19  100002135           2.0       2.0             1.0                       1
20  100002165           2.0      51.0             1.0                       1
21  100002168           1.0       0.0             0.0                       1
22  100002201           2.0      62.0             1.0                       1
23  100002214           2.0     178.0             1.0                       1
24  100002217           2.0     178.0             1.0                       1
25  100002223           2.0      21.0             1.0                       1
26  100002247           2.0     150.0             1.0                       1
27  100002347           1.0     132.0             1.0                       1
28  100002348           2.0     178.0             1.0                       1
29  100002415           2.0      47.0             1.0                       1

In [24]:
kitchen_info['dummy_staple_price']=np.where(kitchen_info['staple_price'].isnull(),0,1)

In [25]:
kitchen_info['dummy_like_num']=np.where(kitchen_info['like_num'].isnull(),0,kitchen_info['dummy_like_num'])

In [26]:
kitchen_info['staple_price']=kitchen_info['staple_price'].fillna(-1)

In [27]:
kitchen_info['like_num']=kitchen_info['like_num'].fillna(0)

In [28]:
kitchen_info.head(30)

,user_id,staple_price,like_num,dummy_like_num,dummy_has_kitchen_info,dummy_staple_price
0,100002020,2.0,11.0,1.0,1,1
1,100002033,1.0,0.0,0.0,1,1
2,100002035,2.0,116.0,1.0,1,1
3,100002036,3.0,40.0,1.0,1,1
4,100002040,2.0,0.0,0.0,1,1
5,100002041,2.0,124.0,1.0,1,1
6,100002044,-1.0,0.0,0.0,0,0
7,100002050,-1.0,0.0,0.0,0,0
8,100002052,3.0,173.0,1.0,1,1
9,100002053,1.0,0.0,0.0,1,1
10,100002078,2.0,0.0,0.0,1,1
11,100002079,3.0,0.0,0.0,1,1
12,100002083,2.0,0.0,0.0,1,1
13,100002085,2.0,128.0,1.0,1,1
14,100002097,2.0,55.0,1.0,1,1
15,100002098,1.0,31.0,1.0,1,1
16,100002108,1.0,113.0,1.0,1,1
17,100002113,3.0,60.0,1.0,1,1
18,100002133,2.0,96.0,1.0,1,1
19,100002135,2.0,2.0,1.0,1,1
20,100002165,2.0,51.0,1.0,1,1
21,100002168,1.0,0.0,0.0,1,1
22,100002201,2.0,62.0,1.0,1,1
23,100002214,2.0,178.0,1.0,1,1
24,100002217,2.0,178.0,1.0,1,1
25,100002223,2.0,21.0,1.0,1,1
26,100002247,2.0,150.0,1.0,1,1
27,100002347,1.0,132.0,1.0,1,1
28,100002348,2.0,178.0,1.0,1,1
29,100002415,2.0,47.0,1.0,1,1

In [30]:
data_final_3=pd.concat([data,kitchen_royalty,kitchen_info],axis=1,sort=False)

In [31]:
list(data_final_3)

['order_sd',
 'active_days',
 'lastgap',
 'avg_gap',
 'min_gap',
 'max_gap',
 'w1_total_orders',
 'w2_total_orders',
 'w3_total_orders',
 'w4_total_orders',
 'w5_total_orders',
 'w6_total_orders',
 'w7_total_orders',
 'label',
 'first_order',
 'last_order',
 'accountLength',
 'overall_time_mean',
 'update2create_time_mean',
 'send2update_time_mean',
 'overall_time_min',
 'update2create_time_min',
 'send2update_time_min',
 'overall_time_max',
 'update2create_time_max',
 'send2update_time_max',
 'intime_rate',
 'last_coupon_fee',
 'last_send_type',
 'order_nums',
 'city_id',
 'sex',
 'age',
 'login_platform_b',
 'app_version_b',
 'age_na',
 'lastgap_na',
 'avg_gap_na',
 'min_gap_na',
 'max_gap_na',
 'overall_time_mean_na',
 'update2create_time_mean_na',
 'send2update_time_mean_na',
 'overall_time_min_na',
 'update2create_time_min_na',
 'send2update_time_min_na',
 'overall_time_max_na',
 'update2create_time_max_na',
 'send2update_time_max_na',
 'pca_1',
 'pca_2',
 'pca_3',
 'pca_4',
 'pca_5',
 'w1_avg_couponworth',
 'w2_avg_couponworth',
 'w3_avg_couponworth',
 'w4_avg_couponworth',
 'w5_avg_couponworth',
 'w6_avg_couponworth',
 'w7_avg_couponworth',
 'w1_max_couponworth',
 'w2_max_couponworth',
 'w3_max_couponworth',
 'w4_max_couponworth',
 'w5_max_couponworth',
 'w6_max_couponworth',
 'w7_max_couponworth',
 'log_order_sd',
 'log_active_days',
 'log_total_orders',
 'log_w1_total_orders',
 'log_w2_total_orders',
 'log_w3_total_orders',
 'log_w4_total_orders',
 'log_w5_total_orders',
 'log_w6_total_orders',
 'log_w7_total_orders',
 'log_first_order',
 'log_last_order',
 'log_accountLength',
 'log_overall_time_mean',
 'log_overall_time_min',
 'log_overall_time_max',
 'log_intime_rate',
 'log_last_coupon_fee',
 'log_order_nums',
 'log_w1_avg_couponworth',
 'log_w2_avg_couponworth',
 'log_w3_avg_couponworth',
 'log_w4_avg_couponworth',
 'log_w5_avg_couponworth',
 'log_w6_avg_couponworth',
 'log_w7_avg_couponworth',
 'log_w1_max_couponworth',
 'log_w2_max_couponworth',
 'log_w3_max_couponworth',
 'log_w4_max_couponworth',
 'log_w5_max_couponworth',
 'log_w6_max_couponworth',
 'log_w7_max_couponworth',
 'dummy_log_lastgap',
 'log_lastgap',
 'dummy_log_avg_gap',
 'log_avg_gap',
 'dummy_log_min_gap',
 'log_min_gap',
 'dummy_log_max_gap',
 'log_max_gap',
 'dummy_log_update2create_time_mean',
 'log_update2create_time_mean',
 'dummy_log_send2update_time_mean',
 'log_send2update_time_mean',
 'dummy_log_update2create_time_min',
 'log_update2create_time_min',
 'dummy_log_send2update_time_min',
 'log_send2update_time_min',
 'dummy_log_update2create_time_max',
 'log_update2create_time_max',
 'dummy_log_send2update_time_max',
 'log_send2update_time_max',
 'user_id',
 'kitchen_royalty',
 'user_id',
 'staple_price',
 'like_num',
 'dummy_like_num',
 'dummy_has_kitchen_info',
 'dummy_staple_price']

In [32]:
data_final_4=data_final_3[['order_sd',
 'active_days',
 'lastgap',
 'avg_gap',
 'min_gap',
 'max_gap',
 'w1_total_orders',
 'w2_total_orders',
 'w3_total_orders',
 'w4_total_orders',
 'w5_total_orders',
 'w6_total_orders',
 'w7_total_orders',
 'label',
 'first_order',
 'last_order',
 'accountLength',
 'overall_time_mean',
 'update2create_time_mean',
 'send2update_time_mean',
 'overall_time_min',
 'update2create_time_min',
 'send2update_time_min',
 'overall_time_max',
 'update2create_time_max',
 'send2update_time_max',
 'intime_rate',
 'last_coupon_fee',
 'last_send_type',
 'order_nums',
 'city_id',
 'sex',
 'age',
 'login_platform_b',
 'app_version_b',
 'age_na',
 'lastgap_na',
 'avg_gap_na',
 'min_gap_na',
 'max_gap_na',
 'overall_time_mean_na',
 'update2create_time_mean_na',
 'send2update_time_mean_na',
 'overall_time_min_na',
 'update2create_time_min_na',
 'send2update_time_min_na',
 'overall_time_max_na',
 'update2create_time_max_na',
 'send2update_time_max_na',
 'w1_avg_couponworth',
 'w2_avg_couponworth',
 'w3_avg_couponworth',
 'w4_avg_couponworth',
 'w5_avg_couponworth',
 'w6_avg_couponworth',
 'w7_avg_couponworth',
 'w1_max_couponworth',
 'w2_max_couponworth',
 'w3_max_couponworth',
 'w4_max_couponworth',
 'w5_max_couponworth',
 'w6_max_couponworth',
 'w7_max_couponworth',
 'log_order_sd',
 'log_active_days',
 'log_total_orders',
 'log_w1_total_orders',
 'log_w2_total_orders',
 'log_w3_total_orders',
 'log_w4_total_orders',
 'log_w5_total_orders',
 'log_w6_total_orders',
 'log_w7_total_orders',
 'log_first_order',
 'log_last_order',
 'log_accountLength',
 'log_overall_time_mean',
 'log_overall_time_min',
 'log_overall_time_max',
 'log_intime_rate',
 'log_last_coupon_fee',
 'log_order_nums',
 'log_w1_avg_couponworth',
 'log_w2_avg_couponworth',
 'log_w3_avg_couponworth',
 'log_w4_avg_couponworth',
 'log_w5_avg_couponworth',
 'log_w6_avg_couponworth',
 'log_w7_avg_couponworth',
 'log_w1_max_couponworth',
 'log_w2_max_couponworth',
 'log_w3_max_couponworth',
 'log_w4_max_couponworth',
 'log_w5_max_couponworth',
 'log_w6_max_couponworth',
 'log_w7_max_couponworth',
 'dummy_log_lastgap',
 'log_lastgap',
 'dummy_log_avg_gap',
 'log_avg_gap',
 'dummy_log_min_gap',
 'log_min_gap',
 'dummy_log_max_gap',
 'log_max_gap',
 'dummy_log_update2create_time_mean',
 'log_update2create_time_mean',
 'dummy_log_send2update_time_mean',
 'log_send2update_time_mean',
 'dummy_log_update2create_time_min',
 'log_update2create_time_min',
 'dummy_log_send2update_time_min',
 'log_send2update_time_min',
 'dummy_log_update2create_time_max',
 'log_update2create_time_max',
 'dummy_log_send2update_time_max',
 'log_send2update_time_max',
 'kitchen_royalty',
 'staple_price',
 'like_num',
 'dummy_like_num',
 'dummy_has_kitchen_info',
 'dummy_staple_price']]

In [33]:
data_final_4.to_csv('new_dataset_w9.csv',index=False)